baseURL = 'https://riccioproductions.github.io/'
languageCode = 'it'
defaultContentLanguage = 'it'
title = 'Riccio Productions'
theme = 'gallery'
timeout = "600s"
enableRobotsTXT = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
  disable = false
 
[taxonomies]
  category = ""
  tag = ""

[params]
  defaultTheme = "dark" 
  logo = "logo.png"
  favicon = "/favicon.ico"
  icon = "/favicon.ico"
  custom_favicon = "/favicon.ico"
  logo_dark = "logo.png"

[params.socialIcons]
   instagram = "https://www.instagram.com/riccio.productions"
   email = "mailto:riccio.prod@gmail.com"
	
[build]
  writeStats = true

[[cascade]]
  [cascade.build]
    publishResources = false